name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Release Binaries
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ./scripts/build-release.sh ${VERSION}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
            dist/*-checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Installation

            ### macOS (Homebrew)
            ```bash
            brew tap dardevelin/get-repo
            brew install get-repo
            ```

            ### macOS (Direct Download)
            Download the signed universal binary: `get-repo-${{ github.ref_name }}-macos-universal-signed.zip`

            ### Linux
            Download the appropriate binary for your architecture and make it executable:
            ```bash
            curl -L https://github.com/dardevelin/get-repo/releases/download/${{ github.ref_name }}/get-repo-${{ github.ref_name }}-linux-amd64.tar.gz | tar xz
            chmod +x get-repo-linux-amd64
            sudo mv get-repo-linux-amd64 /usr/local/bin/get-repo
            ```

            ### Verify checksums
            ```bash
            shasum -a 256 -c get-repo-${{ github.ref_name }}-checksums.txt
            ```

  update-homebrew:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-get-repo
        uses: actions/checkout@v4
        with:
          repository: dardevelin/homebrew-get-repo
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          
      - name: Calculate SHA256
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          URL="https://github.com/dardevelin/get-repo/archive/refs/tags/${VERSION}.tar.gz"
          SHA256=$(curl -sL "$URL" | shasum -a 256 | cut -d' ' -f1)
          echo "SHA256=${SHA256}" >> $GITHUB_ENV
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          sed -i "s|url \".*\"|url \"https://github.com/dardevelin/get-repo/archive/refs/tags/v${VERSION}.tar.gz\"|" Formula/get-repo.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/get-repo.rb

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/get-repo.rb
          git commit -m "Update get-repo to ${VERSION}"
          git push